version: "3"

services:
    iss_tracker:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: iranarang/iss_tracker:1.0
        container_name: iss_tracker-code
        ports:
            - "8080:8080"

