FROM ubuntu:20.04
FROM python:3.9

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
RUN pip install pytest


COPY test_iss_tracker.py /app/test_iss_tracker.py

#ENTRYPOINT ["pytest"]
CMD ["python", "test_iss_tracker.py"]